export const contactConfig = {
  websiteUrl: 'https://nordible.co',
  cardUrl: 'https://nordible.co/card',
  vcardDownloadUrl: '/api/vcard',
  company: {
    name: 'Nordible Technologies',
    legalName: 'Nordible Technologies',
    taglineDe: 'Individuelle Softwareentwicklung, KI-Agenten & Cloud-Architektur',
    taglineEn: 'Custom Software Engineering, AI Agents & Cloud Architecture',
    descriptionDe: 'Ihr Technologiepartner in Frankfurt am Main für moderne Web- & Cloud-Systeme, autonome Agenten und skalierbare Software.',
  },
  founder: {
    name: 'Kabeer Shah',
    firstName: 'Kabeer',
    lastName: 'Shah',
    titleDe: 'Gründer & Solutions Architect',
    titleEn: 'Founder & Solutions Architect',
    email: 'kabeer@nordible.co',
    phone: '+49 1521 1065739',
    linkedin: 'https://www.linkedin.com/in/meetkabeershah/',
    github: 'https://github.com/skbr1234',
  },
  social: {
    linkedin: 'https://www.linkedin.com/company/nordible-co/',
    github: 'https://github.com/nordible',
    instagram: 'https://www.instagram.com/nordible.co/',
    youtube: 'https://www.youtube.com/@nordible',
  },
  phone: {
    display: '+49 1521 1065739',
    raw: '+4915211065739',
    telHref: 'tel:+4915211065739',
  },
  whatsapp: {
    number: '4915211065739',
    chatUrl: "https://wa.me/4915211065739?text=Hello%20Nordible,%20I'd%20like%20to%20discuss%20a%20technology%20project.",
  },
  email: {
    general: 'mail@nordible.co',
    founder: 'kabeer@nordible.co',
    mailToGeneral: 'mailto:mail@nordible.co',
    mailToFounder: 'mailto:kabeer@nordible.co',
  },
  bookingUrl: 'https://calendar.app.google/N4XakE4t9zZVmHqYA',
  address: {
    company: 'Nordible Technologies',
    street: 'Breitlacherstraße 101',
    city: 'Frankfurt am Main',
    postalCode: '60489',
    country: 'Germany',
    full: 'Nordible Technologies, Breitlacherstraße 101, 60489 Frankfurt am Main, Germany',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Breitlacherstra%C3%9Fe+101%2C+60489+Frankfurt+am+Main',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Nordible+Technologies%2C+Breitlacherstra%C3%9Fe+101%2C+60489+Frankfurt+am+Main',
    embedUrl: 'https://maps.google.com/maps?q=Breitlacherstra%C3%9Fe%20101,%2060489%20Frankfurt%20am%20Main&t=&z=15&ie=UTF8&iwloc=&output=embed',
  },
};

